onlyBuiltDependencies:
  - "@getgrit/cli"
  - "@swc/core"
  - "esbuild"
  - "protobufjs"
  - "sharp"
  - "spawn-sync"

patchedDependencies:
  "ts-json-schema-generator@2.9.0": patches/ts-json-schema-generator.patch

updateConfig:
  ignoreDependencies:
    - "@types/vscode"
    - "@types/node"
